### ISSUE TITLE
'cargo install oxigraph-cli' fails

### ISSUE THREAD

**Issue by KonradHoeffner** [oxigraph/oxigraph#1281]
**Describe the bug**
`cargo install oxigraph-cli` fails.

**To Reproduce**
Using the latest version of oxigraph CLI 0.4.10 on Arch Linux.
Error occurs both with Rust 1.87.0 and 1.89.0-nightly.

```
cargo +stable install oxigraph-cli
[...]
 exit status: 0
  exit status: 0

  --- stderr


  error occurred in cc-rs: command did not execute successfully (status code exit status: 1): LC_ALL="C" "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "lz4/lib/" "-Wall" "-Wextra" "-std=c++17" "-Wno-invalid-offsetof" "-msse2" "-msse4.1" "-msse4.2" "-mpclmul" "-mavx2" "-mbmi" "-mlzcnt" "-DNDEBUG=1" "-DLZ4=1" "-DHAVE_SSE42=1" "-DHAVE_PCLMUL=1" "-DHAVE_AVX2=1" "-DHAVE_BMI=1" "-DHAVE_LZCNT=1" "-DOS_LINUX" "-DROCKSDB_PLATFORM_POSIX" "-DROCKSDB_LIB_IO_POSIX" "-DROCKSDB_SUPPORT_THREAD_LOCAL" "-DHAVE_UINT128_EXTENSION=1" "-o" "/tmp/cargo-installDiyrGO/release/build/oxrocksdb-sys-55a0ceaa5ef3227c/out/644b6a24ae2ff5c1-blob_file_meta.o" "-c" "rocksdb/db/blob/blob_file_meta.cc"


error: failed to compile `oxigraph-cli v0.4.10`, intermediate artifacts can be found at `/tmp/cargo-installDiyrGO`.
```

**Comment by Tpt** [comment]
Thank you! I can indeed reproduce it. Interestingly, it seems to not affect CI builds with Ubuntu 24.04 or CentOS 7.

The relevant error is `error: 'uint64_t' does not name a type`

A quick workaround is to use the `rocksdb` package from Arch with the `--features rocksdb-pkg-config` feature flag (see [Oxigraph PKGBUILD file](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=oxigraph#n26))

**Comment by KonradHoeffner** [comment]
Thank you for the workaround! Both versions from AUR also work: [oxigraph](https://aur.archlinux.org/packages/oxigraph) and oxigraph-bin.

**Comment by Tpt** [comment]
Should be fixed by v0.4.11. Please reopen if it's not the case.

**Comment by KonradHoeffner** [comment]
Thanks for the swift fix! However unfortunately it still fails with 0.4.11.
@Tpt: I do not have the permissions to reopen the issue.
It's taking several minutes (Intel Core i3 1115G4) for `Building [=======================> ] 248/253: oxrocksdb-sys(build)` and then it fails:

```
~$ cargo install oxigraph-cli
    Updating crates.io index
  Downloaded oxigraph-cli v0.4.11
  Downloaded 1 crate (1.3MiB) in 1.95s
  Installing oxigraph-cli v0.4.11
    Updating crates.io index
     Locking 211 packages to latest compatible versions
      Adding i_float v1.7.0 (available: v1.13.0)
      Adding i_overlay v2.0.5 (available: v2.2.0)
      Adding i_shape v1.7.0 (available: v1.12.0)
      Adding oxhttp v0.2.7 (available: v0.3.0)
      Adding rand v0.8.5 (available: v0.9.1)
  Downloaded foreign-types-shared v0.1.1
  Downloaded foreign-types v0.3.2
  Downloaded float_next_after v1.0.0
  Downloaded openssl-macros v0.1.1
  Downloaded i_key_sort v0.2.0
  Downloaded peg-runtime v0.8.5
  Downloaded approx v0.5.1
  Downloaded foldhash v0.1.5
  Downloaded clap_mangen v0.2.26
  Downloaded hash32 v0.3.1
  Downloaded cexpr v0.6.0
  Downloaded writeable v0.6.1
  Downloaded spargeo v0.1.8
  Downloaded synstructure v0.13.2
  Downloaded i_float v1.7.0
  Downloaded roff v0.2.2
  Downloaded idna_adapter v1.2.1
  Downloaded zerovec-derive v0.11.1
  Downloaded rustc-hash v2.1.1
  Downloaded siphasher v1.0.1
  Downloaded i_shape v1.7.0
  Downloaded peg v0.8.5
  Downloaded i_tree v0.8.3
  Downloaded potential_utf v0.1.2
  Downloaded sparopt v0.2.1
  Downloaded tinystr v0.8.1
  Downloaded yoke-derive v0.8.0
  Downloaded native-tls v0.2.14
  Downloaded dashmap v6.1.0
  Downloaded peg-macros v0.8.5
  Downloaded md-5 v0.10.6
  Downloaded jobserver v0.1.33
  Downloaded yoke v0.8.0
  Downloaded libloading v0.8.7
  Downloaded oxhttp v0.2.7
  Downloaded spargebra v0.3.5
  Downloaded sparesults v0.2.5
  Downloaded oxsdatatypes v0.2.2
  Downloaded litemap v0.8.0
  Downloaded geo-traits v0.3.0
  Downloaded spareval v0.1.4
  Downloaded clap_complete v4.5.50
  Downloaded geographiclib-rs v0.2.5
  Downloaded geo-types v0.7.16
  Downloaded clang-sys v1.8.1
  Downloaded rstar v0.12.2
  Downloaded icu_provider v2.0.0
  Downloaded icu_normalizer v2.0.0
  Downloaded icu_properties v2.0.1
  Downloaded prettyplease v0.2.32
  Downloaded icu_normalizer_data v2.0.0
  Downloaded zerotrie v0.2.2
  Downloaded oxigraph v0.4.11
  Downloaded icu_locale_core v2.0.0
  Downloaded icu_collections v2.0.0
  Downloaded openssl-sys v0.9.108
  Downloaded flate2 v1.1.1
  Downloaded heapless v0.8.0
  Downloaded cc v1.2.23
  Downloaded zerovec v0.11.2
  Downloaded itertools v0.11.0
  Downloaded hashbrown v0.15.3
  Downloaded libm v0.2.15
  Downloaded geojson v0.24.2
  Downloaded i_overlay v2.0.5
  Downloaded wkt v0.14.0
  Downloaded icu_properties_data v2.0.1
  Downloaded bindgen v0.71.1
  Downloaded geo v0.30.0
  Downloaded openssl v0.10.72
  Downloaded spade v2.13.1
  Downloaded robust v1.2.0
  Downloaded earcutr v0.4.3
  Downloaded oxrocksdb-sys v0.4.11
  Downloaded 74 crates (9.6MiB) in 2.32s (largest was `oxrocksdb-sys` at 4.2MiB)
   Compiling proc-macro2 v1.0.95
   Compiling unicode-ident v1.0.18
   Compiling libc v0.2.172
   Compiling cfg-if v1.0.0
   Compiling stable_deref_trait v1.2.0
   Compiling autocfg v1.4.0
   Compiling zerocopy v0.8.25
   Compiling smallvec v1.15.0
   Compiling quote v1.0.40
   Compiling shlex v1.3.0
   Compiling crossbeam-utils v0.8.21
   Compiling thiserror v2.0.12
   Compiling syn v2.0.101
   Compiling jobserver v0.1.33
   Compiling getrandom v0.2.16
   Compiling libm v0.2.15
   Compiling cc v1.2.23
   Compiling rand_core v0.6.4
   Compiling ppv-lite86 v0.2.21
   Compiling memchr v2.7.4
   Compiling rand_chacha v0.3.1
   Compiling num-traits v0.2.19
   Compiling serde v1.0.219
   Compiling version_check v0.9.5
   Compiling typenum v1.18.0
   Compiling generic-array v0.14.7
   Compiling rand v0.8.5
   Compiling synstructure v0.13.2
   Compiling rayon-core v1.12.1
   Compiling oxiri v0.2.11
   Compiling oxilangtag v0.1.5
   Compiling crossbeam-epoch v0.9.18
   Compiling either v1.15.0
   Compiling glob v0.3.2
   Compiling zerofrom-derive v0.1.6
   Compiling yoke-derive v0.8.0
   Compiling thiserror-impl v2.0.12
   Compiling zerovec-derive v0.11.1
   Compiling zerofrom v0.1.6
   Compiling displaydoc v0.2.5
   Compiling yoke v0.8.0
   Compiling serde_derive v1.0.219
   Compiling zerovec v0.11.2
   Compiling oxsdatatypes v0.2.2
   Compiling vcpkg v0.2.15
   Compiling tinystr v0.8.1
   Compiling oxrdf v0.2.4
   Compiling writeable v0.6.1
   Compiling pkg-config v0.3.32
   Compiling litemap v0.8.0
   Compiling openssl-sys v0.9.108
   Compiling icu_locale_core v2.0.0
   Compiling potential_utf v0.1.2
   Compiling zerotrie v0.2.2
   Compiling clang-sys v1.8.1
   Compiling crossbeam-deque v0.8.6
   Compiling prettyplease v0.2.32
   Compiling icu_properties_data v2.0.1
   Compiling heapless v0.8.0
   Compiling icu_normalizer_data v2.0.0
   Compiling byteorder v1.5.0
   Compiling hash32 v0.3.1
   Compiling icu_provider v2.0.0
   Compiling icu_collections v2.0.0
   Compiling utf8parse v0.2.2
   Compiling minimal-lexical v0.2.1
   Compiling regex-syntax v0.8.5
   Compiling nom v7.1.3
   Compiling libloading v0.8.7
   Compiling anstyle-parse v0.2.6
   Compiling rayon v1.10.0
   Compiling regex-automata v0.4.9
   Compiling block-buffer v0.10.4
   Compiling crypto-common v0.1.6
   Compiling heck v0.5.0
   Compiling peg-runtime v0.8.5
   Compiling colorchoice v1.0.3
   Compiling anstyle-query v1.1.2
   Compiling log v0.4.27
   Compiling bindgen v0.71.1
   Compiling anstyle v1.0.10
   Compiling is_terminal_polyfill v1.70.1
   Compiling itertools v0.13.0
   Compiling anstream v0.6.18
   Compiling peg-macros v0.8.5
   Compiling regex v1.11.1
   Compiling clap_derive v4.5.32
   Compiling digest v0.10.7
   Compiling icu_normalizer v2.0.0
   Compiling rstar v0.12.2
   Compiling icu_properties v2.0.1
   Compiling cexpr v0.6.0
   Compiling approx v0.5.1
   Compiling quick-xml v0.37.5
   Compiling bitflags v2.9.1
   Compiling rustc-hash v2.1.1
   Compiling once_cell v1.21.3
   Compiling json-event-parser v0.2.2
   Compiling clap_lex v0.7.4
   Compiling strsim v0.11.1
   Compiling foreign-types-shared v0.1.1
   Compiling openssl v0.10.72
   Compiling peg v0.8.5
   Compiling foreign-types v0.3.2
   Compiling clap_builder v4.5.38
   Compiling geo-types v0.7.16
   Compiling idna_adapter v1.2.1
   Compiling openssl-macros v0.1.1
   Compiling aho-corasick v1.1.3
   Compiling lock_api v0.4.12
   Compiling percent-encoding v2.3.1
   Compiling utf8_iter v1.0.4
   Compiling httparse v1.10.1
   Compiling adler2 v2.0.0
   Compiling parking_lot_core v0.9.10
   Compiling cpufeatures v0.2.17
   Compiling native-tls v0.2.14
   Compiling oxrocksdb-sys v0.4.11
   Compiling miniz_oxide v0.8.8
   Compiling idna v1.0.3
   Compiling form_urlencoded v1.2.1
   Compiling clap v4.5.38
   Compiling spargebra v0.3.5
   Compiling i_float v1.7.0
   Compiling crc32fast v1.4.2
   Compiling thiserror v1.0.69
   Compiling foldhash v0.1.5
   Compiling allocator-api2 v0.2.21
   Compiling equivalent v1.0.2
   Compiling serde_json v1.0.140
   Compiling scopeguard v1.2.0
   Compiling openssl-probe v0.1.6
   Compiling hashbrown v0.15.3
   Compiling sparopt v0.2.1
   Compiling flate2 v1.1.1
   Compiling i_shape v1.7.0
   Compiling url v2.5.4
   Compiling sha1 v0.10.6
   Compiling sha2 v0.10.9
   Compiling sparesults v0.2.5
   Compiling oxjsonld v0.1.0
   Compiling oxrdfxml v0.1.7
   Compiling md-5 v0.10.6
   Compiling oxttl v0.1.8
   Compiling thiserror-impl v1.0.69
   Compiling itertools v0.11.0
   Compiling hashbrown v0.14.5
   Compiling itoa v1.0.15
   Compiling i_tree v0.8.3
   Compiling robust v1.2.0
   Compiling roff v0.2.2
   Compiling i_key_sort v0.2.0
   Compiling ryu v1.0.20
   Compiling hex v0.4.3
   Compiling spareval v0.1.4
   Compiling i_overlay v2.0.5
   Compiling clap_mangen v0.2.26
   Compiling dashmap v6.1.0
   Compiling spade v2.13.1
   Compiling earcutr v0.4.3
   Compiling oxrdfio v0.1.8
   Compiling oxhttp v0.2.7
   Compiling clap_complete v4.5.50
   Compiling geo-traits v0.3.0
   Compiling geographiclib-rs v0.2.5
   Compiling anyhow v1.0.98
   Compiling siphasher v1.0.1
   Compiling float_next_after v1.0.0
   Compiling geo v0.30.0
   Compiling wkt v0.14.0
   Compiling oxigraph-cli v0.4.11
   Compiling geojson v0.24.2
warning: oxrocksdb-sys@0.4.11: In member function 'void rocksdb::{anonymous}::LevelCompactionBuilder::SetupInitialFiles()',
warning: oxrocksdb-sys@0.4.11:     inlined from 'rocksdb::Compaction* rocksdb::{anonymous}::LevelCompactionBuilder::PickCompaction()' at rocksdb/db/compaction/compaction_picker_level.cc:513:20,
warning: oxrocksdb-sys@0.4.11:     inlined from 'virtual rocksdb::Compaction* rocksdb::LevelCompactionPicker::PickCompaction(const std::string&, const rocksdb::MutableCFOptions&, const rocksdb::MutableDBOptions&, const std::vector<long unsigned int>&, const rocksdb::SnapshotChecker*, rocksdb::VersionStorageInfo*, rocksdb::LogBuffer*)' at rocksdb/db/compaction/compaction_picker_level.cc:985:32:
warning: oxrocksdb-sys@0.4.11: rocksdb/db/compaction/compaction_picker_level.cc:287:42: warning: '*(std::value_type*)((char*)&expired_files + offsetof(rocksdb::autovector<std::pair<int, rocksdb::FileMetaData*>, 8>,rocksdb::autovector<std::pair<int, rocksdb::FileMetaData*>, 8>::buf_[0])).std::pair<int, rocksdb::FileMetaData*>::first' may be used uninitialized [-Wmaybe-uninitialized]
warning: oxrocksdb-sys@0.4.11:   287 |     start_level_ = expired_files.front().first;
warning: oxrocksdb-sys@0.4.11:       |                    ~~~~~~~~~~~~~~~~~~~~~~^~~~~
warning: oxrocksdb-sys@0.4.11: rocksdb/db/compaction/compaction_picker_level.cc: In member function 'virtual rocksdb::Compaction* rocksdb::LevelCompactionPicker::PickCompaction(const std::string&, const rocksdb::MutableCFOptions&, const rocksdb::MutableDBOptions&, const std::vector<long unsigned int>&, const rocksdb::SnapshotChecker*, rocksdb::VersionStorageInfo*, rocksdb::LogBuffer*)':
warning: oxrocksdb-sys@0.4.11: rocksdb/db/compaction/compaction_picker_level.cc:285:10: note: 'expired_files' declared here
warning: oxrocksdb-sys@0.4.11:   285 |     auto expired_files = vstorage_->ExpiredTtlFiles();
warning: oxrocksdb-sys@0.4.11:       |          ^~~~~~~~~~~~~
error: failed to run custom build command for `oxrocksdb-sys v0.4.11`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installKtFB5g/release/build/oxrocksdb-sys-64349fdeb66a77cf/build-script-build` (exit status: 101)
  --- stdout
  OUT_DIR = Some(/tmp/cargo-installKtFB5g/release/build/oxrocksdb-sys-df4cf4c419620388/out)
  OPT_LEVEL = Some(3)
  TARGET = Some(x86_64-unknown-linux-gnu)
  HOST = Some(x86_64-unknown-linux-gnu)
  cargo:rerun-if-env-changed=CC_x86_64-unknown-linux-gnu
  CC_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CC_x86_64_unknown_linux_gnu
  CC_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  RUSTC_WRAPPER = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some(false)
  CARGO_CFG_TARGET_FEATURE = Some(adx,aes,avx,avx2,avx512bitalg,avx512bw,avx512cd,avx512dq,avx512f,avx512ifma,avx512vbmi,avx512vbmi2,avx512vl,avx512vnni,avx512vp2intersect,avx512vpopcntdq,bmi1,bmi2,cmpxchg16b,ermsb,f16c,fma,fxsr,gfni,kl,lahfsahf,lzcnt,movbe,pclmulqdq,popcnt,prfchw,rdrand,rdseed,sha,sse,sse2,sse3,sse4.1,sse4.2,ssse3,vaes,vpclmulqdq,widekl,x87,xsave,xsavec,xsaveopt,xsaves)
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_unknown_linux_gnu
  CFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64-unknown-linux-gnu
  CFLAGS_x86_64-unknown-linux-gnu = None
  CARGO_ENCODED_RUSTFLAGS = Some(-Ctarget-cpu=native)
  exit status: 0
  exit status: 0
  exit status: 0
  exit status: 0
  cargo:rerun-if-env-changed=AR_x86_64-unknown-linux-gnu
  AR_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=AR_x86_64_unknown_linux_gnu
  AR_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_AR
  HOST_AR = None
  cargo:rerun-if-env-changed=AR
  AR = None
  cargo:rerun-if-env-changed=ARFLAGS
  ARFLAGS = None
  cargo:rerun-if-env-changed=HOST_ARFLAGS
  HOST_ARFLAGS = None
  cargo:rerun-if-env-changed=ARFLAGS_x86_64_unknown_linux_gnu
  ARFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=ARFLAGS_x86_64-unknown-linux-gnu
  ARFLAGS_x86_64-unknown-linux-gnu = None
  cargo:rustc-link-lib=static=lz4
  cargo:rustc-link-search=native=/tmp/cargo-installKtFB5g/release/build/oxrocksdb-sys-df4cf4c419620388/out
  OUT_DIR = Some(/tmp/cargo-installKtFB5g/release/build/oxrocksdb-sys-df4cf4c419620388/out)
  OPT_LEVEL = Some(3)
  TARGET = Some(x86_64-unknown-linux-gnu)
  HOST = Some(x86_64-unknown-linux-gnu)
  cargo:rerun-if-env-changed=CXX_x86_64-unknown-linux-gnu
  CXX_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CXX_x86_64_unknown_linux_gnu
  CXX_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CXX
  HOST_CXX = None
  cargo:rerun-if-env-changed=CXX
  CXX = None
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  RUSTC_WRAPPER = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some(false)
  CARGO_CFG_TARGET_FEATURE = Some(adx,aes,avx,avx2,avx512bitalg,avx512bw,avx512cd,avx512dq,avx512f,avx512ifma,avx512vbmi,avx512vbmi2,avx512vl,avx512vnni,avx512vp2intersect,avx512vpopcntdq,bmi1,bmi2,cmpxchg16b,ermsb,f16c,fma,fxsr,gfni,kl,lahfsahf,lzcnt,movbe,pclmulqdq,popcnt,prfchw,rdrand,rdseed,sha,sse,sse2,sse3,sse4.1,sse4.2,ssse3,vaes,vpclmulqdq,widekl,x87,xsave,xsavec,xsaveopt,xsaves)
  cargo:rerun-if-env-changed=CXXFLAGS
  CXXFLAGS = None
  cargo:rerun-if-env-changed=HOST_CXXFLAGS
  HOST_CXXFLAGS = None
  cargo:rerun-if-env-changed=CXXFLAGS_x86_64_unknown_linux_gnu
  CXXFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=CXXFLAGS_x86_64-unknown-linux-gnu
  CXXFLAGS_x86_64-unknown-linux-gnu = None
  CARGO_ENCODED_RUSTFLAGS = Some(-Ctarget-cpu=native)
  OUT_DIR = Some(/tmp/cargo-installKtFB5g/release/build/oxrocksdb-sys-df4cf4c419620388/out)
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  TARGET = Some(x86_64-unknown-linux-gnu)
  CARGO_CFG_TARGET_FEATURE = Some(adx,aes,avx,avx2,avx512bitalg,avx512bw,avx512cd,avx512dq,avx512f,avx512ifma,avx512vbmi,avx512vbmi2,avx512vl,avx512vnni,avx512vp2intersect,avx512vpopcntdq,bmi1,bmi2,cmpxchg16b,ermsb,f16c,fma,fxsr,gfni,kl,lahfsahf,lzcnt,movbe,pclmulqdq,popcnt,prfchw,rdrand,rdseed,sha,sse,sse2,sse3,sse4.1,sse4.2,ssse3,vaes,vpclmulqdq,widekl,x87,xsave,xsavec,xsaveopt,xsaves)
  HOST = Some(x86_64-unknown-linux-gnu)
  cargo:rerun-if-env-changed=CXXFLAGS
  CXXFLAGS = None
  cargo:rerun-if-env-changed=HOST_CXXFLAGS
  HOST_CXXFLAGS = None
  cargo:rerun-if-env-changed=CXXFLAGS_x86_64_unknown_linux_gnu
  CXXFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=CXXFLAGS_x86_64-unknown-linux-gnu
  CXXFLAGS_x86_64-unknown-linux-gnu = None
  OUT_DIR = Some(/tmp/cargo-installKtFB5g/release/build/oxrocksdb-sys-df4cf4c419620388/out)
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  TARGET = Some(x86_64-unknown-linux-gnu)
  CARGO_CFG_TARGET_FEATURE = Some(adx,aes,avx,avx2,avx512bitalg,avx512bw,avx512cd,avx512dq,avx512f,avx512ifma,avx512vbmi,avx512vbmi2,avx512vl,avx512vnni,avx512vp2intersect,avx512vpopcntdq,bmi1,bmi2,cmpxchg16b,ermsb,f16c,fma,fxsr,gfni,kl,lahfsahf,lzcnt,movbe,pclmulqdq,popcnt,prfchw,rdrand,rdseed,sha,sse,sse2,sse3,sse4.1,sse4.2,ssse3,vaes,vpclmulqdq,widekl,x87,xsave,xsavec,xsaveopt,xsaves)
  HOST = Some(x86_64-unknown-linux-gnu)
  cargo:rerun-if-env-changed=CXXFLAGS
  CXXFLAGS = None
  cargo:rerun-if-env-changed=HOST_CXXFLAGS
  HOST_CXXFLAGS = None
  cargo:rerun-if-env-changed=CXXFLAGS_x86_64_unknown_linux_gnu
  CXXFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=CXXFLAGS_x86_64-unknown-linux-gnu
  CXXFLAGS_x86_64-unknown-linux-gnu = None
  OUT_DIR = Some(/tmp/cargo-installKtFB5g/release/build/oxrocksdb-sys-df4cf4c419620388/out)
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  TARGET = Some(x86_64-unknown-linux-gnu)
  CARGO_CFG_TARGET_FEATURE = Some(adx,aes,avx,avx2,avx512bitalg,avx512bw,avx512cd,avx512dq,avx512f,avx512ifma,avx512vbmi,avx512vbmi2,avx512vl,avx512vnni,avx512vp2intersect,avx512vpopcntdq,bmi1,bmi2,cmpxchg16b,ermsb,f16c,fma,fxsr,gfni,kl,lahfsahf,lzcnt,movbe,pclmulqdq,popcnt,prfchw,rdrand,rdseed,sha,sse,sse2,sse3,sse4.1,sse4.2,ssse3,vaes,vpclmulqdq,widekl,x87,xsave,xsavec,xsaveopt,xsaves)
  HOST = Some(x86_64-unknown-linux-gnu)
  cargo:rerun-if-env-changed=CXXFLAGS
  CXXFLAGS = None
  cargo:rerun-if-env-changed=HOST_CXXFLAGS
  HOST_CXXFLAGS = None
  cargo:rerun-if-env-changed=CXXFLAGS_x86_64_unknown_linux_gnu
  CXXFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=CXXFLAGS_x86_64-unknown-linux-gnu
  CXXFLAGS_x86_64-unknown-linux-gnu = None
  OUT_DIR = Some(/tmp/cargo-installKtFB5g/release/build/oxrocksdb-sys-df4cf4c419620388/out)
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  TARGET = Some(x86_64-unknown-linux-gnu)
  CARGO_CFG_TARGET_FEATURE = Some(adx,aes,avx,avx2,avx512bitalg,avx512bw,avx512cd,avx512dq,avx512f,avx512ifma,avx512vbmi,avx512vbmi2,avx512vl,avx512vnni,avx512vp2intersect,avx512vpopcntdq,bmi1,bmi2,cmpxchg16b,ermsb,f16c,fma,fxsr,gfni,kl,lahfsahf,lzcnt,movbe,pclmulqdq,popcnt,prfchw,rdrand,rdseed,sha,sse,sse2,sse3,sse4.1,sse4.2,ssse3,vaes,vpclmulqdq,widekl,x87,xsave,xsavec,xsaveopt,xsaves)
  HOST = Some(x86_64-unknown-linux-gnu)
  cargo:rerun-if-env-changed=CXXFLAGS
  CXXFLAGS = None
  cargo:rerun-if-env-changed=HOST_CXXFLAGS
  HOST_CXXFLAGS = None
  cargo:rerun-if-env-changed=CXXFLAGS_x86_64_unknown_linux_gnu
  CXXFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=CXXFLAGS_x86_64-unknown-linux-gnu
  CXXFLAGS_x86_64-unknown-linux-gnu = None
  OUT_DIR = Some(/tmp/cargo-installKtFB5g/release/build/oxrocksdb-sys-df4cf4c419620388/out)
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  TARGET = Some(x86_64-unknown-linux-gnu)
  CARGO_CFG_TARGET_FEATURE = Some(adx,aes,avx,avx2,avx512bitalg,avx512bw,avx512cd,avx512dq,avx512f,avx512ifma,avx512vbmi,avx512vbmi2,avx512vl,avx512vnni,avx512vp2intersect,avx512vpopcntdq,bmi1,bmi2,cmpxchg16b,ermsb,f16c,fma,fxsr,gfni,kl,lahfsahf,lzcnt,movbe,pclmulqdq,popcnt,prfchw,rdrand,rdseed,sha,sse,sse2,sse3,sse4.1,sse4.2,ssse3,vaes,vpclmulqdq,widekl,x87,xsave,xsavec,xsaveopt,xsaves)
  HOST = Some(x86_64-unknown-linux-gnu)
  cargo:rerun-if-env-changed=CXXFLAGS
  CXXFLAGS = None
  cargo:rerun-if-env-changed=HOST_CXXFLAGS
  HOST_CXXFLAGS = None
  cargo:rerun-if-env-changed=CXXFLAGS_x86_64_unknown_linux_gnu
  CXXFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=CXXFLAGS_x86_64-unknown-linux-gnu
  CXXFLAGS_x86_64-unknown-linux-gnu = None
  OUT_DIR = Some(/tmp/cargo-installKtFB5g/release/build/oxrocksdb-sys-df4cf4c419620388/out)
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  TARGET = Some(x86_64-unknown-linux-gnu)
  CARGO_CFG_TARGET_FEATURE = Some(adx,aes,avx,avx2,avx512bitalg,avx512bw,avx512cd,avx512dq,avx512f,avx512ifma,avx512vbmi,avx512vbmi2,avx512vl,avx512vnni,avx512vp2intersect,avx512vpopcntdq,bmi1,bmi2,cmpxchg16b,ermsb,f16c,fma,fxsr,gfni,kl,lahfsahf,lzcnt,movbe,pclmulqdq,popcnt,prfchw,rdrand,rdseed,sha,sse,sse2,sse3,sse4.1,sse4.2,ssse3,vaes,vpclmulqdq,widekl,x87,xsave,xsavec,xsaveopt,xsaves)
  HOST = Some(x86_64-unknown-linux-gnu)
  cargo:rerun-if-env-changed=CXXFLAGS
  CXXFLAGS = None
  cargo:rerun-if-env-changed=HOST_CXXFLAGS
  HOST_CXXFLAGS = None
  cargo:rerun-if-env-changed=CXXFLAGS_x86_64_unknown_linux_gnu
  CXXFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=CXXFLAGS_x86_64-unknown-linux-gnu
  CXXFLAGS_x86_64-unknown-linux-gnu = None
  OUT_DIR = Some(/tmp/cargo-installKtFB5g/release/build/oxrocksdb-sys-df4cf4c419620388/out)
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  TARGET = Some(x86_64-unknown-linux-gnu)
  CARGO_CFG_TARGET_FEATURE = Some(adx,aes,avx,avx2,avx512bitalg,avx512bw,avx512cd,avx512dq,avx512f,avx512ifma,avx512vbmi,avx512vbmi2,avx512vl,avx512vnni,avx512vp2intersect,avx512vpopcntdq,bmi1,bmi2,cmpxchg16b,ermsb,f16c,fma,fxsr,gfni,kl,lahfsahf,lzcnt,movbe,pclmulqdq,popcnt,prfchw,rdrand,rdseed,sha,sse,sse2,sse3,sse4.1,sse4.2,ssse3,vaes,vpclmulqdq,widekl,x87,xsave,xsavec,xsaveopt,xsaves)
  HOST = Some(x86_64-unknown-linux-gnu)
  cargo:rerun-if-env-changed=CXXFLAGS
  CXXFLAGS = None
  cargo:rerun-if-env-changed=HOST_CXXFLAGS
  HOST_CXXFLAGS = None
  cargo:rerun-if-env-changed=CXXFLAGS_x86_64_unknown_linux_gnu
  CXXFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=CXXFLAGS_x86_64-unknown-linux-gnu
  CXXFLAGS_x86_64-unknown-linux-gnu = None
  exit status: 0
[...]
  exit status: 0
  cargo:warning=In member function 'void rocksdb::{anonymous}::LevelCompactionBuilder::SetupInitialFiles()',
  cargo:warning=    inlined from 'rocksdb::Compaction* rocksdb::{anonymous}::LevelCompactionBuilder::PickCompaction()' at rocksdb/db/compaction/compaction_picker_level.cc:513:20,
  cargo:warning=    inlined from 'virtual rocksdb::Compaction* rocksdb::LevelCompactionPicker::PickCompaction(const std::string&, const rocksdb::MutableCFOptions&, const rocksdb::MutableDBOptions&, const std::vector<long unsigned int>&, const rocksdb::SnapshotChecker*, rocksdb::VersionStorageInfo*, rocksdb::LogBuffer*)' at rocksdb/db/compaction/compaction_picker_level.cc:985:32:
  cargo:warning=rocksdb/db/compaction/compaction_picker_level.cc:287:42: warning: '*(std::value_type*)((char*)&expired_files + offsetof(rocksdb::autovector<std::pair<int, rocksdb::FileMetaData*>, 8>,rocksdb::autovector<std::pair<int, rocksdb::FileMetaData*>, 8>::buf_[0])).std::pair<int, rocksdb::FileMetaData*>::first' may be used uninitialized [-Wmaybe-uninitialized]
  cargo:warning=  287 |     start_level_ = expired_files.front().first;
  cargo:warning=      |                    ~~~~~~~~~~~~~~~~~~~~~~^~~~~
  cargo:warning=rocksdb/db/compaction/compaction_picker_level.cc: In member function 'virtual rocksdb::Compaction* rocksdb::LevelCompactionPicker::PickCompaction(const std::string&, const rocksdb::MutableCFOptions&, const rocksdb::MutableDBOptions&, const std::vector<long unsigned int>&, const rocksdb::SnapshotChecker*, rocksdb::VersionStorageInfo*, rocksdb::LogBuffer*)':
  cargo:warning=rocksdb/db/compaction/compaction_picker_level.cc:285:10: note: 'expired_files' declared here
  cargo:warning=  285 |     auto expired_files = vstorage_->ExpiredTtlFiles();
  cargo:warning=      |          ^~~~~~~~~~~~~
  exit status: 0
  [...]
exit status: 0
  cargo:rerun-if-env-changed=AR_x86_64-unknown-linux-gnu
  AR_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=AR_x86_64_unknown_linux_gnu
  AR_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_AR
  HOST_AR = None
  cargo:rerun-if-env-changed=AR
  AR = None
  cargo:rerun-if-env-changed=ARFLAGS
  ARFLAGS = None
  cargo:rerun-if-env-changed=HOST_ARFLAGS
  HOST_ARFLAGS = None
  cargo:rerun-if-env-changed=ARFLAGS_x86_64_unknown_linux_gnu
  ARFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=ARFLAGS_x86_64-unknown-linux-gnu
  ARFLAGS_x86_64-unknown-linux-gnu = None
  cargo:rustc-link-lib=static=rocksdb
  cargo:rustc-link-search=native=/tmp/cargo-installKtFB5g/release/build/oxrocksdb-sys-df4cf4c419620388/out
  cargo:rerun-if-env-changed=CXXSTDLIB_x86_64-unknown-linux-gnu
  CXXSTDLIB_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CXXSTDLIB_x86_64_unknown_linux_gnu
  CXXSTDLIB_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CXXSTDLIB
  HOST_CXXSTDLIB = None
  cargo:rerun-if-env-changed=CXXSTDLIB
  CXXSTDLIB = None
  cargo:rustc-link-lib=stdc++
  OUT_DIR = Some(/tmp/cargo-installKtFB5g/release/build/oxrocksdb-sys-df4cf4c419620388/out)
  OPT_LEVEL = Some(3)
  TARGET = Some(x86_64-unknown-linux-gnu)
  HOST = Some(x86_64-unknown-linux-gnu)
  cargo:rerun-if-env-changed=CXX_x86_64-unknown-linux-gnu
  CXX_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CXX_x86_64_unknown_linux_gnu
  CXX_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CXX
  HOST_CXX = None
  cargo:rerun-if-env-changed=CXX
  CXX = None
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  RUSTC_WRAPPER = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some(false)
  CARGO_CFG_TARGET_FEATURE = Some(adx,aes,avx,avx2,avx512bitalg,avx512bw,avx512cd,avx512dq,avx512f,avx512ifma,avx512vbmi,avx512vbmi2,avx512vl,avx512vnni,avx512vp2intersect,avx512vpopcntdq,bmi1,bmi2,cmpxchg16b,ermsb,f16c,fma,fxsr,gfni,kl,lahfsahf,lzcnt,movbe,pclmulqdq,popcnt,prfchw,rdrand,rdseed,sha,sse,sse2,sse3,sse4.1,sse4.2,ssse3,vaes,vpclmulqdq,widekl,x87,xsave,xsavec,xsaveopt,xsaves)
  cargo:rerun-if-env-changed=CXXFLAGS
  CXXFLAGS = None
  cargo:rerun-if-env-changed=HOST_CXXFLAGS
  HOST_CXXFLAGS = None
  cargo:rerun-if-env-changed=CXXFLAGS_x86_64_unknown_linux_gnu
  CXXFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=CXXFLAGS_x86_64-unknown-linux-gnu
  CXXFLAGS_x86_64-unknown-linux-gnu = None
  CARGO_ENCODED_RUSTFLAGS = Some(-Ctarget-cpu=native)
  cargo:rerun-if-env-changed=AR_x86_64-unknown-linux-gnu
  AR_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=AR_x86_64_unknown_linux_gnu
  AR_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_AR
  HOST_AR = None
  cargo:rerun-if-env-changed=AR
  AR = None
  cargo:rerun-if-env-changed=ARFLAGS
  ARFLAGS = None
  cargo:rerun-if-env-changed=HOST_ARFLAGS
  HOST_ARFLAGS = None
  cargo:rerun-if-env-changed=ARFLAGS_x86_64_unknown_linux_gnu
  ARFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=ARFLAGS_x86_64-unknown-linux-gnu
  ARFLAGS_x86_64-unknown-linux-gnu = None
  cargo:rustc-link-lib=static=oxrocksdb_api
  cargo:rustc-link-search=native=/tmp/cargo-installKtFB5g/release/build/oxrocksdb-sys-df4cf4c419620388/out
  cargo:rerun-if-env-changed=CXXSTDLIB_x86_64-unknown-linux-gnu
  CXXSTDLIB_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CXXSTDLIB_x86_64_unknown_linux_gnu
  CXXSTDLIB_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CXXSTDLIB
  HOST_CXXSTDLIB = None
  cargo:rerun-if-env-changed=CXXSTDLIB
  CXXSTDLIB = None
  cargo:rustc-link-lib=stdc++
  cargo:rerun-if-changed=api/

  --- stderr

  thread 'main' panicked at /home/konrad/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bindgen-0.71.1/lib.rs:604:27:
  Unable to find libclang: "couldn't find any valid shared libraries matching: ['libclang.so', 'libclang-*.so', 'libclang.so.*', 'libclang-*.so.*'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: failed to compile `oxigraph-cli v0.4.11`, intermediate artifacts can be found at `/tmp/cargo-installKtFB5g`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```

**Comment by Tpt** [comment]
@KonradHoeffner Hey! I think the key is:

```
  Unable to find libclang: "couldn't find any valid shared libraries matching: ['libclang.so', 'libclang-*.so', 'libclang.so.*', 'libclang-*.so.*'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

You need to install [`clang`](https://archlinux.org/packages/extra/x86_64/clang/) to generate the Rust bindings for RocksDB.

**Comment by KonradHoeffner** [comment]
Ah, that was missing from the requirements in the README.md:

> You need to have [a recent stable version of Rust and Cargo installed](https://www.rust-lang.org/tools/install).

I will create a PR to add this.
